# Generated by Django 5.2.8 on 2025-12-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=123, max_length=150),
            preserve_default=False,
        ),
    ]
