# Generated by Django 5.2.8 on 2025-12-02 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
