# Generated by Django 5.2.8 on 2025-12-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Bottle Art', 'Bottle Art'), ('Wall Art', 'Wall Art'), ('Kitchen', 'Kitchen')], default='Bottle Art', max_length=50),
        ),
    ]
